breatheapp/config/routes.rb
Rails.application.routes.draw do
  resources :medicine_plans
  resources :plan_zones
  resources :peak_flows
  resources :user_care_plans
  resources :users
  root 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

breatheapp/app/models/medicine_plan.rb
class MedicinePlan < ApplicationRecord
    belongs_to :plan_zone
    
    validates :dosage_num, presence: true
    validates :dosage_measure, presence: true
    
    # validates :frequency, presence: true # todo i would like to set a default to "as needed"
    # todo change frequency setup, frankly
end

breatheapp/app/controllers/medicine_plans_controller.rb
class MedicinePlansController < ApplicationController
  before_action :set_medicine_plan, only: [:show, :edit, :update, :destroy]

  # GET /medicine_plans
  # GET /medicine_plans.json
  def index
    @medicine_plans = MedicinePlan.all
  end

  # GET /medicine_plans/1
  # GET /medicine_plans/1.json
  def show
  end

  # GET /medicine_plans/new
  def new
    @medicine_plan = MedicinePlan.new
  end

  # GET /medicine_plans/1/edit
  def edit
  end

  # POST /medicine_plans
  # POST /medicine_plans.json
  def create
    @medicine_plan = MedicinePlan.new(medicine_plan_params)

    respond_to do |format|
      if @medicine_plan.save
        format.html { redirect_to @medicine_plan, notice: 'Medicine plan was successfully created.' }
        format.json { render :show, status: :created, location: @medicine_plan }
      else
        format.html { render :new }
        format.json { render json: @medicine_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medicine_plans/1
  # PATCH/PUT /medicine_plans/1.json
  def update
    respond_to do |format|
      if @medicine_plan.update(medicine_plan_params)
        format.html { redirect_to @medicine_plan, notice: 'Medicine plan was successfully updated.' }
        format.json { render :show, status: :ok, location: @medicine_plan }
      else
        format.html { render :edit }
        format.json { render json: @medicine_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medicine_plans/1
  # DELETE /medicine_plans/1.json
  def destroy
    @medicine_plan.destroy
    respond_to do |format|
      format.html { redirect_to medicine_plans_url, notice: 'Medicine plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medicine_plan
      @medicine_plan = MedicinePlan.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def medicine_plan_params
      params.require(:medicine_plan).permit(:name, :dosageNum, :dosageMeasure, :frequency)
    end
end

breatheapp/app/helpers/medicine_plans_helper.rb
module MedicinePlansHelper
end

breatheapp/app/views/medicine_plans/_form.html.erb
<%= form_with(model: medicine_plan) do |form| %>
  <% if medicine_plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(medicine_plan.errors.count, "error") %> prohibited this medicine_plan from being saved:</h2>

      <ul>
        <% medicine_plan.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :dosageNum %>
    <%= form.text_field :dosageNum %>
  </div>

  <div class="field">
    <%= form.label :dosageMeasure %>
    <%= form.text_field :dosageMeasure %>
  </div>

  <div class="field">
    <%= form.label :frequency %>
    <%= form.text_field :frequency %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

breatheapp/app/views/medicine_plans/edit.html.erb
<h1>Editing Medicine Plan</h1>

<%= render 'form', medicine_plan: @medicine_plan %>

<%= link_to 'Show', @medicine_plan %> |
<%= link_to 'Back', medicine_plans_path %>

breatheapp/app/views/medicine_plans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Medicine Plans</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Dosagenum</th>
      <th>Dosagemeasure</th>
      <th>Frequency</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @medicine_plans.each do |medicine_plan| %>
      <tr>
        <td><%= medicine_plan.name %></td>
        <td><%= medicine_plan.dosageNum %></td>
        <td><%= medicine_plan.dosageMeasure %></td>
        <td><%= medicine_plan.frequency %></td>
        <td><%= link_to 'Show', medicine_plan %></td>
        <td><%= link_to 'Edit', edit_medicine_plan_path(medicine_plan) %></td>
        <td><%= link_to 'Destroy', medicine_plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Medicine Plan', new_medicine_plan_path %>

breatheapp/app/views/medicine_plans/new.html.erb
<h1>New Medicine Plan</h1>

<%= render 'form', medicine_plan: @medicine_plan %>

<%= link_to 'Back', medicine_plans_path %>

breatheapp/app/views/medicine_plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @medicine_plan.name %>
</p>

<p>
  <strong>Dosagenum:</strong>
  <%= @medicine_plan.dosageNum %>
</p>

<p>
  <strong>Dosagemeasure:</strong>
  <%= @medicine_plan.dosageMeasure %>
</p>

<p>
  <strong>Frequency:</strong>
  <%= @medicine_plan.frequency %>
</p>

<%= link_to 'Edit', edit_medicine_plan_path(@medicine_plan) %> |
<%= link_to 'Back', medicine_plans_path %>