breatheapp/config/routes.rb
Rails.application.routes.draw do
  resources :medicine_plans
  resources :plan_zones
  resources :peak_flows
  resources :user_care_plans
  resources :users
  root 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

breatheapp/app/models/user.rb
class User < ApplicationRecord
    # has_many :patients # todo not sure how to do a recursive user id, just doing integers for now
    has_one :user_care_plan, dependent: :destroy
    
    validates :name, presence: true
end

breatheapp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :loginState, :admin, :patients, :care_plan)
    end
end

breatheapp/app/helpers/users_helper.rb
module UsersHelper
end

breatheapp/app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :loginState %>
    <%= form.check_box :loginState %>
  </div>

  <div class="field">
    <%= form.label :admin %>
    <%= form.check_box :admin %>
  </div>

  <div class="field">
    <%= form.label :patients %>
    <%= form.text_field :patients %>
  </div>

  <div class="field">
    <%= form.label :carePlan %>
    <%= form.text_field :carePlan %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

breatheapp/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

breatheapp/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Loginstate</th>
      <th>Admin</th>
      <th>Patients</th>
      <th>Careplan</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.loginState %></td>
        <td><%= user.admin %></td>
        <td><%= user.patients %></td>
        <td><%= user.care_plan %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

breatheapp/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

breatheapp/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Login State:</strong>
  <%= @user.login_state %>
</p>

<p>
  <strong>Admin:</strong>
  <%= @user.admin %>
</p>

<p>
  <strong>Patients:</strong>
  <%= @user.patients %>
</p>

<p>
  <strong>Care plan:</strong>
  <%= @user.care_plan %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>