breatheapp/config/routes.rb
Rails.application.routes.draw do
  resources :medicine_plans
  resources :plan_zones
  resources :peak_flows
  resources :user_care_plans
  resources :users
  root 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

breatheapp/app/models/plan_zone.rb
class PlanZone < ApplicationRecord
    belongs_to :user_care_plan
    has_many :medicine_plan, dependent: :destroy
    
    validates :color, presence: true # Todo validate within 'green', 'red', or 'yellow'
    # todo validate that not both of peakflow_min/max are nullish
    validates :description, presence: true
    
    # This one's required at a minimum, an emergency situation
    validates :quick_medicine_plan, presence: true
end

breatheapp/app/controllers/plan_zones_controller.rb
class PlanZonesController < ApplicationController
  before_action :set_plan_zone, only: [:show, :edit, :update, :destroy]

  # GET /plan_zones
  # GET /plan_zones.json
  def index
    @plan_zones = PlanZone.all
  end

  # GET /plan_zones/1
  # GET /plan_zones/1.json
  def show
  end

  # GET /plan_zones/new
  def new
    @plan_zone = PlanZone.new
  end

  # GET /plan_zones/1/edit
  def edit
  end

  # POST /plan_zones
  # POST /plan_zones.json
  def create
    @plan_zone = PlanZone.new(plan_zone_params)

    respond_to do |format|
      if @plan_zone.save
        format.html { redirect_to @plan_zone, notice: 'Plan zone was successfully created.' }
        format.json { render :show, status: :created, location: @plan_zone }
      else
        format.html { render :new }
        format.json { render json: @plan_zone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plan_zones/1
  # PATCH/PUT /plan_zones/1.json
  def update
    respond_to do |format|
      if @plan_zone.update(plan_zone_params)
        format.html { redirect_to @plan_zone, notice: 'Plan zone was successfully updated.' }
        format.json { render :show, status: :ok, location: @plan_zone }
      else
        format.html { render :edit }
        format.json { render json: @plan_zone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plan_zones/1
  # DELETE /plan_zones/1.json
  def destroy
    @plan_zone.destroy
    respond_to do |format|
      format.html { redirect_to plan_zones_url, notice: 'Plan zone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan_zone
      @plan_zone = PlanZone.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def plan_zone_params
      params.require(:plan_zone).permit(:color, :description, :symptoms, :peakflowMin, :peakflowMax, :controlMedicinePlan, :quickMedicinePlan, :physicalActivityPlan)
    end
end

breatheapp/app/helpers/plan_zones_helper.rb
module PlanZonesHelper
end

breatheapp/app/views/plan_zones/_form.html.erb
<%= form_with(model: plan_zone) do |form| %>
  <% if plan_zone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plan_zone.errors.count, "error") %> prohibited this plan_zone from being saved:</h2>

      <ul>
        <% plan_zone.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :symptoms %>
    <%= form.text_field :symptoms %>
  </div>

  <div class="field">
    <%= form.label :peakflowMin %>
    <%= form.text_field :peakflowMin %>
  </div>

  <div class="field">
    <%= form.label :peakflowMax %>
    <%= form.text_field :peakflowMax %>
  </div>

  <div class="field">
    <%= form.label :controlMedicinePlan %>
    <%= form.text_field :controlMedicinePlan %>
  </div>

  <div class="field">
    <%= form.label :quickMedicinePlan %>
    <%= form.text_field :quickMedicinePlan %>
  </div>

  <div class="field">
    <%= form.label :physicalActivityPlan %>
    <%= form.text_field :physicalActivityPlan %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

breatheapp/app/views/plan_zones/edit.html.erb
<h1>Editing Plan Zone</h1>

<%= render 'form', plan_zone: @plan_zone %>

<%= link_to 'Show', @plan_zone %> |
<%= link_to 'Back', plan_zones_path %>

breatheapp/app/views/plan_zones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Plan Zones</h1>

<table>
  <thead>
    <tr>
      <th>Color</th>
      <th>Description</th>
      <th>Symptoms</th>
      <th>Peakflowmin</th>
      <th>Peakflowmax</th>
      <th>Controlmedicineplan</th>
      <th>Quickmedicineplan</th>
      <th>Physicalactivityplan</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plan_zones.each do |plan_zone| %>
      <tr>
        <td><%= plan_zone.color %></td>
        <td><%= plan_zone.description %></td>
        <td><%= plan_zone.symptoms %></td>
        <td><%= plan_zone.peakflowMin %></td>
        <td><%= plan_zone.peakflowMax %></td>
        <td><%= plan_zone.controlMedicinePlan %></td>
        <td><%= plan_zone.quickMedicinePlan %></td>
        <td><%= plan_zone.physicalActivityPlan %></td>
        <td><%= link_to 'Show', plan_zone %></td>
        <td><%= link_to 'Edit', edit_plan_zone_path(plan_zone) %></td>
        <td><%= link_to 'Destroy', plan_zone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plan Zone', new_plan_zone_path %>

breatheapp/app/views/plan_zones/new.html.erb
<h1>New Plan Zone</h1>

<%= render 'form', plan_zone: @plan_zone %>

<%= link_to 'Back', plan_zones_path %>

breatheapp/app/views/plan_zones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Color:</strong>
  <%= @plan_zone.color %>
</p>

<p>
  <strong>Description:</strong>
  <%= @plan_zone.description %>
</p>

<p>
  <strong>Symptoms:</strong>
  <%= @plan_zone.symptoms %>
</p>

<p>
  <strong>Peakflowmin:</strong>
  <%= @plan_zone.peakflowMin %>
</p>

<p>
  <strong>Peakflowmax:</strong>
  <%= @plan_zone.peakflowMax %>
</p>

<p>
  <strong>Controlmedicineplan:</strong>
  <%= @plan_zone.controlMedicinePlan %>
</p>

<p>
  <strong>Quickmedicineplan:</strong>
  <%= @plan_zone.quickMedicinePlan %>
</p>

<p>
  <strong>Physicalactivityplan:</strong>
  <%= @plan_zone.physicalActivityPlan %>
</p>

<%= link_to 'Edit', edit_plan_zone_path(@plan_zone) %> |
<%= link_to 'Back', plan_zones_path %>