breatheapp/config/routes.rb
Rails.application.routes.draw do
  resources :medicine_plans
  resources :plan_zones
  resources :peak_flows
  resources :user_care_plans
  resources :users
  root 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

breatheapp/app/models/user_care_plan.rb
class UserCarePlan < ApplicationRecord
    has_many :peak_flow, dependent: :destroy
    has_many :plan_zone, dependent: :destroy
    has_many :emergency_contacts, dependent: :destroy
    
    validates :severity_confirmation, presence: true
end

breatheapp/app/controllers/user_care_plans_controller.rb
class UserCarePlansController < ApplicationController
  before_action :set_user_care_plan, only: [:show, :edit, :update, :destroy]

  # GET /user_care_plans
  # GET /user_care_plans.json
  def index
    @user_care_plans = UserCarePlan.all
  end

  # GET /user_care_plans/1
  # GET /user_care_plans/1.json
  def show
  end

  # GET /user_care_plans/new
  def new
    @user_care_plan = UserCarePlan.new
  end

  # GET /user_care_plans/1/edit
  def edit
  end

  # POST /user_care_plans
  # POST /user_care_plans.json
  def create
    @user_care_plan = UserCarePlan.new(user_care_plan_params)

    respond_to do |format|
      if @user_care_plan.save
        format.html { redirect_to @user_care_plan, notice: 'User care plan was successfully created.' }
        format.json { render :show, status: :created, location: @user_care_plan }
      else
        format.html { render :new }
        format.json { render json: @user_care_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_care_plans/1
  # PATCH/PUT /user_care_plans/1.json
  def update
    respond_to do |format|
      if @user_care_plan.update(user_care_plan_params)
        format.html { redirect_to @user_care_plan, notice: 'User care plan was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_care_plan }
      else
        format.html { render :edit }
        format.json { render json: @user_care_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_care_plans/1
  # DELETE /user_care_plans/1.json
  def destroy
    @user_care_plan.destroy
    respond_to do |format|
      format.html { redirect_to user_care_plans_url, notice: 'User care plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_care_plan
      @user_care_plan = UserCarePlan.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_care_plan_params
      params.require(:user_care_plan).permit(:triggerList, :severityClassification, :peakFlowHistory, :zones, :emergencyContacts)
    end
end

breatheapp/app/helpers/user_care_plans_helper.rb
module UserCarePlansHelper
end

breatheapp/app/views/user_care_plans/_form.html.erb
<%= form_with(model: user_care_plan) do |form| %>
  <% if user_care_plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_care_plan.errors.count, "error") %> prohibited this user_care_plan from being saved:</h2>

      <ul>
        <% user_care_plan.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :triggerList %>
    <%= form.text_field :triggerList %>
  </div>

  <div class="field">
    <%= form.label :severityClassification %>
    <%= form.text_field :severityClassification %>
  </div>

  <div class="field">
    <%= form.label :peakFlowHistory %>
    <%= form.text_field :peakFlowHistory %>
  </div>

  <div class="field">
    <%= form.label :zones %>
    <%= form.text_field :zones %>
  </div>

  <div class="field">
    <%= form.label :emergencyContacts %>
    <%= form.text_field :emergencyContacts %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

breatheapp/app/views/user_care_plans/edit.html.erb
<h1>Editing User Care Plan</h1>

<%= render 'form', user_care_plan: @user_care_plan %>

<%= link_to 'Show', @user_care_plan %> |
<%= link_to 'Back', user_care_plans_path %>

breatheapp/app/views/user_care_plans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Care Plans</h1>

<table>
  <thead>
    <tr>
      <th>Triggerlist</th>
      <th>Severityclassification</th>
      <th>Peakflowhistory</th>
      <th>Zones</th>
      <th>Emergencycontacts</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_care_plans.each do |user_care_plan| %>
      <tr>
        <td><%= user_care_plan.triggerList %></td>
        <td><%= user_care_plan.severityClassification %></td>
        <td><%= user_care_plan.peakFlowHistory %></td>
        <td><%= user_care_plan.zones %></td>
        <td><%= user_care_plan.emergencyContacts %></td>
        <td><%= link_to 'Show', user_care_plan %></td>
        <td><%= link_to 'Edit', edit_user_care_plan_path(user_care_plan) %></td>
        <td><%= link_to 'Destroy', user_care_plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Care Plan', new_user_care_plan_path %>

breatheapp/app/views/user_care_plans/new.html.erb
<h1>New User Care Plan</h1>

<%= render 'form', user_care_plan: @user_care_plan %>

<%= link_to 'Back', user_care_plans_path %>

breatheapp/app/views/user_care_plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Triggerlist:</strong>
  <%= @user_care_plan.triggerList %>
</p>

<p>
  <strong>Severityclassification:</strong>
  <%= @user_care_plan.severityClassification %>
</p>

<p>
  <strong>Peakflowhistory:</strong>
  <%= @user_care_plan.peakFlowHistory %>
</p>

<p>
  <strong>Zones:</strong>
  <%= @user_care_plan.zones %>
</p>

<p>
  <strong>Emergencycontacts:</strong>
  <%= @user_care_plan.emergencyContacts %>
</p>

<%= link_to 'Edit', edit_user_care_plan_path(@user_care_plan) %> |
<%= link_to 'Back', user_care_plans_path %>